FROM golang:alpine as build-env

ENV GO111MODULE=on

RUN apk update && apk add bash ca-certificates git gcc g++ libc-dev

RUN mkdir /docker_test
RUN mkdir -p /docker_test/chatpb

COPY ./chatpb/chat.pb.go /docker_test/chatpb
COPY ./main.go /docker_test

COPY go.mod .
COPY go.sum .

RUN go mod download

RUN go build -o docker_test .

CMD ./docker_test

